# Generated by Django 5.0.1 on 2024-01-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
