# Generated by Django 5.0.1 on 2024-02-01 16:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
