# Generated by Django 5.0.1 on 2024-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderapp', '0002_rename_book_cartitem_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
