# Generated by Django 5.0.1 on 2024-01-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderapp', '0003_rename_book_orderitem_book_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_title', to='Wanderapp.book'),
        ),
    ]
