# Generated by Django 5.0.1 on 2024-01-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderapp', '0004_alter_orderitem_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
