# Generated by Django 5.0.1 on 2024-01-29 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderapp', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(5)),
        ),
    ]
